name: fingerprint_attendance
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  crypto: ^3.0.0
  email_validator: ^2.0.1
  image_picker: ^0.8.4+5
  mailer: ^5.1.0
  http: ^0.13.3
  google_maps_flutter: ^2.1.1
  flutter_map: ^3.1.0
  latlong2: ^0.8.0
  geolocator: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  hive_generator: ^1.1.0
  image_picker_for_web: ^2.1.7
  intl: ^0.17.0
  table_calendar: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/arrow_mm.png
    - assets/company_logo.jpg
    - assets/Apartments.PNG
    - assets/Nouna.jpg
    - assets/MMLogo.jpg
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
        - asset: fonts/NotoSans-Bold.ttf
          weight: 700
    - family: NotoSansSymbols
      fonts:
        - asset: fonts/NotoSansSymbols-Regular.ttf
        - asset: fonts/NotoSansSymbols-Bold.ttf
          weight: 700
